const path = require('path')
const qs = require('querystring')
const loaderUtils = require('loader-utils')
const {cwd} = require('process')

const mixinGeneratorPath = require.resolve('./runtime/mixinGenerator')
const match = require('./match')

module.exports = function (source, sourceMap) {
  // 获取配置数据
  const options = loaderUtils.getOptions(this)

  const moduleMap =
    typeof options.map === 'string' ? require(path.resolve(cwd(), options.map)) : options.map
  if (!moduleMap) return

  const log = options.log ? console.log : () => {}

  const {resourceQuery, resourcePath} = this
  const rawQuery = resourceQuery.slice(1)
  const query = qs.parse(rawQuery)

  if (query.blockType === 'inject-store') {
    // 处理注入的自定义块
    const stringifyRequest = (path) => loaderUtils.stringifyRequest(this, path)

    const map = JSON.parse(source)

    const importCode = []
    const pathListCode = []
    const moduleListCode = []
    Object.entries(map).forEach(([path, url]) => {
      const name = '_' + path.replace(/\//g, '_')
      importCode.push(`import ${name} from '${url}`)
      pathListCode.push(path)
      moduleListCode.push(name)
    })

    let code = `/* generated by lazy-store-loader */
${importCode.join('\n')}
import _mixinGenerator from ${stringifyRequest(`!${mixinGeneratorPath}`)}

export default function (component) {
  if(!component.options.mixins)
    component.options.mixins = []
  const mixin = _mixinGenerator([${pathListCode.join('\n')}], [${moduleListCode.join('\n')}])
  component.options.mixins.push(mixin)
}`
    return code
  } else {
    // 注入自定义块
    const result = {}
    // 解析获取模块
    const paths = match(source)
    paths.forEach((p) => {
      if (moduleMap[p]) result[p] = moduleMap[p]
    })
    const size = Object.keys(result).length

    log(`[lazy-store-loader] ${resourcePath}: ${JSON.stringify(paths)}`)

    // 注入代码
    const code = size ? source + `<inject-store>${JSON.stringify(result)}</inject-store>` : source

    this.callback(null, code, sourceMap)
  }
}
