const path = require('path')
const qs = require('querystring')
const loaderUtils = require('loader-utils')

const mixinGeneratorPath = require.resolve('./runtime/mixinGenerator')

module.exports = function (source) {
  const {resourceQuery} = this

  const query = qs.parse(resourceQuery)

  if (!query.path || !query.url) {
    this.emitError(new Error(`[lazy-store-loader] missing 'path' or 'url' attr.`))
    return ''
  }

  const stringifyRequest = (path) => loaderUtils.stringifyRequest(this, path)

  let code = `/* generated by lazy-store-loader */
import _storeModule from '${query.url}'
import _mixinGenerator from ${stringifyRequest(`!${mixinGeneratorPath}`)}

export default function (component) {
  if(!component.options.mixins)
    component.options.mixins = []
  const mixin = _mixinGenerator('${query.path}', _storeModule)
  component.options.mixins.push(mixin)
}`
  return code
}
